In [10]:
%load_ext autoreload
%autoreload 2
from matk.conformer import get_atoms, pre_optimize

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Guess a conformer geometry of a molecule

In [11]:
smiles = "c1ccc2c(c1)[nH]c1ccc(-n3c4ccccc4c4ccccc43)cc12"
atoms = get_atoms(smiles)
print(atoms.positions)

[[-3.67283773 -5.40308691  0.0275949 ]
 [-4.04776105 -4.11102723  0.38826576]
 [-3.16146248 -3.03998788  0.22608506]
 [-1.87785421 -3.27659138 -0.30835921]
 [-1.53333813 -4.58091779 -0.65979384]
 [-2.40656498 -5.66409966 -0.50430054]
 [-0.24910122 -4.53992831 -1.14921668]
 [ 0.24677906 -3.25721051 -1.12964452]
 [ 1.49215455 -2.76587716 -1.53599898]
 [ 1.72563622 -1.39321645 -1.39739697]
 [ 0.746491   -0.54557629 -0.86840489]
 [ 1.01022666  0.85083302 -0.73268391]
 [ 0.70460883  1.62472097  0.3900026 ]
 [ 0.15816286  1.28178533  1.64528651]
 [-0.02032581  2.28531813  2.60205061]
 [ 0.35043548  3.59615541  2.33538864]
 [ 0.92571306  3.92873062  1.10678719]
 [ 1.11930793  2.93197483  0.12435194]
 [ 1.69649099  2.95017575 -1.17890857]
 [ 2.27446646  3.97365778 -1.96284874]
 [ 2.73189215  3.69197746 -3.25218687]
 [ 2.60855467  2.41152428 -3.77385968]
 [ 2.04330316  1.38113177 -3.01676826]
 [ 1.61577195  1.65671035 -1.70034538]
 [-0.49740643 -1.06021395 -0.46666287]
 [-0.75189007 -2.44198514

You can pre-optimization of the geometry using EMT()

In [12]:
atoms = pre_optimize(atoms)
print(atoms.positions)

[[-1.57360328 -2.91665604 -0.58802185]
 [-1.39502478 -2.72276503  1.0290459 ]
 [-1.62961052 -2.00936207 -1.67551395]
 [-1.09952191 -1.64002168  0.17804189]
 [-0.2234898  -3.19343594  0.27732856]
 [-1.38889065 -3.83984146  0.47997169]
 [-0.60129844 -1.3399675  -2.20197273]
 [-0.20387126 -2.39548508 -1.03219148]
 [ 0.49241362 -1.11450301 -1.15372075]
 [-0.38714167  0.0712477  -1.77651435]
 [-0.26495057 -0.30579163 -0.02129769]
 [ 1.22187799 -0.84132736  0.3016546 ]
 [-0.34885783  1.26563556 -0.81178825]
 [ 1.10312895  0.42370257  0.82485338]
 [-0.27347385  1.02819061  0.63052521]
 [ 0.94947806  1.78956742  1.08690272]
 [ 0.1267295   2.3451892   0.18341972]
 [ 1.57209817  1.72196743 -0.20415814]
 [ 0.57687422  2.44132716 -1.21459106]
 [ 2.14288911  2.44362042 -1.35743549]
 [ 1.35764732  2.2749239  -2.41733686]
 [ 1.98054805  1.15459604 -1.67756572]
 [ 0.52145906  1.1905564  -2.11732697]
 [ 1.06300002  0.35120707 -0.79133994]
 [ 0.36480035 -1.87104872  0.44226291]
 [-1.39324586 -0.76244198

In [13]:
from matk.calculators.nwchem import NWChem

calc = NWChem(label='nwchem',
              dft={
                'maxiter': 2000,
                'xc': 'B3LYP',
              }, 
              basis='6-31+G*',
             )
atoms.calc = calc                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                               
e1 = atoms.get_potential_energy()                                                                                                                                                                                                                                                          
print(f'test molecule energy: {e1:5.2f} eV')

--------------------------------------------------------------------------
mpirun could not find anything to do.

It is possible that you forgot to specify how many processes to run
via the "-np" argument.
--------------------------------------------------------------------------


CalculationFailed: Calculator "nwchem" failed with command "mpirun -np 8 nwchem_openmpi nwchem.nwi >> nwchem.nwo 2> nwchem.err" failed in /matk/scratch with error code 1